apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-api-config
data:
  FLASK_ENV: "production"
  FLASK_DEBUG: "false"
  FLASK_HOST: "0.0.0.0"
  FLASK_PORT: "5000"
  APP_NAME: "Flask Kluster API"
  APP_VERSION: "1.0.0"
  LOG_LEVEL: "INFO"
